//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelMerge.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelMerge.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Apply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_ApplyCell {
            get {
                return ResourceManager.GetString("Button_ApplyCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract Diff과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_ExtractDiff {
            get {
                return ResourceManager.GetString("Button_ExtractDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge Destination과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_MergeDestination {
            get {
                return ResourceManager.GetString("Button_MergeDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge Source과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_MergeSource {
            get {
                return ResourceManager.GetString("Button_MergeSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Excel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Button_SaveExcel {
            get {
                return ResourceManager.GetString("Button_SaveExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output Log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ContextMenu_BuildCellBaseLog {
            get {
                return ResourceManager.GetString("ContextMenu_BuildCellBaseLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Build Column Base Log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ContextMenu_BuildColumnBaseLog {
            get {
                return ResourceManager.GetString("ContextMenu_BuildColumnBaseLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Build Row Base Log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ContextMenu_BuildRowBaseLog {
            get {
                return ResourceManager.GetString("ContextMenu_BuildRowBaseLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy as CSV과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ContextMenu_CopyAsCsv {
            get {
                return ResourceManager.GetString("ContextMenu_CopyAsCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy as TSV과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ContextMenu_CopyAsTsv {
            get {
                return ResourceManager.GetString("ContextMenu_CopyAsTsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extract diff with this row as column header.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ContextMenu_DiffAsHeader {
            get {
                return ResourceManager.GetString("ContextMenu_DiffAsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ↑Reset Column Header과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ContextMenu_ResetColumnHeader {
            get {
                return ResourceManager.GetString("ContextMenu_ResetColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ←Reset Row Header과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ContextMenu_ResetRowHeader {
            get {
                return ResourceManager.GetString("ContextMenu_ResetRowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ↑Set Column Header과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ContextMenu_SetColumnHeader {
            get {
                return ResourceManager.GetString("ContextMenu_SetColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ←Set Row Header과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ContextMenu_SetRowHeader {
            get {
                return ResourceManager.GetString("ContextMenu_SetRowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ${LEFT} → ${RIGHT}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DefaultColumnBaseLogFormat {
            get {
                return ResourceManager.GetString("DefaultColumnBaseLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Changed &quot;${ROW}&quot;&apos;s &quot;${COL}&quot; to &quot;${RIGHT}&quot; from &quot;${LEFT}&quot;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DefaultLogFormat {
            get {
                return ResourceManager.GetString("DefaultLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;${ROW}&quot; was added.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DefaultLogFormatAddedRow {
            get {
                return ResourceManager.GetString("DefaultLogFormatAddedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;${ROW}&quot; was removed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DefaultLogFormatRemovedRow {
            get {
                return ResourceManager.GetString("DefaultLogFormatRemovedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ${LEFT} → ${RIGHT}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string DefaultRowBaseLogFormat {
            get {
                return ResourceManager.GetString("DefaultRowBaseLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Behavior과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GroupBox_Behavior {
            get {
                return ResourceManager.GetString("GroupBox_Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display Format과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GroupBox_DisplayFormat {
            get {
                return ResourceManager.GetString("GroupBox_DisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log Format과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GroupBox_LogFormat {
            get {
                return ResourceManager.GetString("GroupBox_LogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GroupBox_ReadSetting {
            get {
                return ResourceManager.GetString("GroupBox_ReadSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Style과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GroupBox_Style {
            get {
                return ResourceManager.GetString("GroupBox_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Added Color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_AddedColor {
            get {
                return ResourceManager.GetString("Label_AddedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Added Row Log Format과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_AddedRowLogFormat {
            get {
                return ResourceManager.GetString("Label_AddedRowLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Added Rows({0})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_AddedRows {
            get {
                return ResourceManager.GetString("Label_AddedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always expand cell diff과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_AlwaysExpandCellDiff {
            get {
                return ResourceManager.GetString("Label_AlwaysExpandCellDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color Modified Row과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ColorModifiedRow {
            get {
                return ResourceManager.GetString("Label_ColorModifiedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Base Log Format과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ColumnBaseLogFormat {
            get {
                return ResourceManager.GetString("Label_ColumnBaseLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Header Color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ColumnHeaderColor {
            get {
                return ResourceManager.GetString("Label_ColumnHeaderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Width과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ColumnWidth {
            get {
                return ResourceManager.GetString("Label_ColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fit Cell Height과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_FitRowHeight {
            get {
                return ResourceManager.GetString("Label_FitRowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Focus first diff when extracted과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_FocusFirstDiff {
            get {
                return ResourceManager.GetString("Label_FocusFirstDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore File Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_IgnoreFileSetting {
            get {
                return ResourceManager.GetString("Label_IgnoreFileSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified Cell Log Format과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_LogFormat {
            get {
                return ResourceManager.GetString("Label_LogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max Row Height과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_MaxRowHeight {
            get {
                return ResourceManager.GetString("Label_MaxRowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min Row Height과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_MinRowHeight {
            get {
                return ResourceManager.GetString("Label_MinRowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified Cells({0})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ModifiedCells {
            get {
                return ResourceManager.GetString("Label_ModifiedCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified Color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ModifiedColor {
            get {
                return ResourceManager.GetString("Label_ModifiedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified Row Color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ModifiedRowColor {
            get {
                return ResourceManager.GetString("Label_ModifiedRowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Modified Rows({0})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_ModifiedRows {
            get {
                return ResourceManager.GetString("Label_ModifiedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show dialog if no diff과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_NotifyEqual {
            get {
                return ResourceManager.GetString("Label_NotifyEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Removed Color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_RemovedColor {
            get {
                return ResourceManager.GetString("Label_RemovedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Removed Row Log Format과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_RemovedRowLogFormat {
            get {
                return ResourceManager.GetString("Label_RemovedRowLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Removed Rows({0})과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_RemovedRows {
            get {
                return ResourceManager.GetString("Label_RemovedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Base Log Format과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_RowBaseLogFormat {
            get {
                return ResourceManager.GetString("Label_RowBaseLogFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Colors과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_RowColor {
            get {
                return ResourceManager.GetString("Label_RowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Header Color과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_RowHeaderColor {
            get {
                return ResourceManager.GetString("Label_RowHeaderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Height과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_RowlHeight {
            get {
                return ResourceManager.GetString("Label_RowlHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip first blank columns과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_SkipFirstBlankColumns {
            get {
                return ResourceManager.GetString("Label_SkipFirstBlankColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip first blank rows과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_SkipFirstBlankRows {
            get {
                return ResourceManager.GetString("Label_SkipFirstBlankRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trim last blank columns과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TrimLastBlankColumns {
            get {
                return ResourceManager.GetString("Label_TrimLastBlankColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trim last blank rows과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Label_TrimLastBlankRows {
            get {
                return ResourceManager.GetString("Label_TrimLastBlankRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Console과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_Console {
            get {
                return ResourceManager.GetString("MenuItem_Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Execute external command과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_ExeExternalCmd {
            get {
                return ResourceManager.GetString("MenuItem_ExeExternalCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   External Commands과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_ExternalCommands {
            get {
                return ResourceManager.GetString("MenuItem_ExternalCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_FileSettings {
            get {
                return ResourceManager.GetString("MenuItem_FileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_GeneralSetting {
            get {
                return ResourceManager.GetString("MenuItem_GeneralSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open as Dst File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_OpenAsDstFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenAsDstFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open as Src File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_OpenAsSrcFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenAsSrcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open dst File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_OpenDstFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenDstFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open src file과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_OpenSrcFile {
            get {
                return ResourceManager.GetString("MenuItem_OpenSrcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent Files과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_RecentFiles {
            get {
                return ResourceManager.GetString("MenuItem_RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recent File Sets과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_RecentFileSets {
            get {
                return ResourceManager.GetString("MenuItem_RecentFileSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string MenuItem_View {
            get {
                return ResourceManager.GetString("MenuItem_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no difference.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_NoDiff {
            get {
                return ResourceManager.GetString("Message_NoDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please restart to apply the changes.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Reboot {
            get {
                return ResourceManager.GetString("Message_Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extracting Diff ...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Msg_ExtractingDiff {
            get {
                return ResourceManager.GetString("Msg_ExtractingDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sheet index of the applied file settings is out of range.
        ///Will use first sheet.
        ///If you don&apos;t want to apply file settings, enable &quot;Ignore File Setting&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Msg_OutofSheetRange {
            get {
                return ResourceManager.GetString("Msg_OutofSheetRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reading Files ...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Msg_ReadingFiles {
            get {
                return ResourceManager.GetString("Msg_ReadingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not be displayed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Msg_Undisplayable {
            get {
                return ResourceManager.GetString("Msg_Undisplayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There are too many records. Display only around diff.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Msg_WarnSize {
            get {
                return ResourceManager.GetString("Msg_WarnSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RadioButton_ShowAll {
            get {
                return ResourceManager.GetString("RadioButton_ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Only Diff과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string RadioButton_ShowOnlyDiff {
            get {
                return ResourceManager.GetString("RadioButton_ShowOnlyDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + Down과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Shortcut_Ctrl_Down {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + I과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Shortcut_Ctrl_I {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + K과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Shortcut_Ctrl_K {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + L과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Shortcut_Ctrl_L {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_L", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + Left과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Shortcut_Ctrl_Left {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + O과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Shortcut_Ctrl_O {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_O", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + Right과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Shortcut_Ctrl_Right {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ctrl + Up과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Shortcut_Ctrl_Up {
            get {
                return ResourceManager.GetString("Shortcut_Ctrl_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F8과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Shortcut_F8 {
            get {
                return ResourceManager.GetString("Shortcut_F8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   F9과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Shortcut_F9 {
            get {
                return ResourceManager.GetString("Shortcut_F9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit External Command과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_ExternalCommandEditorWindow {
            get {
                return ResourceManager.GetString("Title_ExternalCommandEditorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   External Commands과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_ExternalCommandsWindow {
            get {
                return ResourceManager.GetString("Title_ExternalCommandsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit File Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_FileSettingEditorWindow {
            get {
                return ResourceManager.GetString("Title_FileSettingEditorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_FileSettingsWindow {
            get {
                return ResourceManager.GetString("Title_FileSettingsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General Settings과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Title_GeneralSettingWindow {
            get {
                return ResourceManager.GetString("Title_GeneralSettingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dst File Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolTip_DstFilePath {
            get {
                return ResourceManager.GetString("ToolTip_DstFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dst Sheet과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolTip_DstSheet {
            get {
                return ResourceManager.GetString("ToolTip_DstSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Src File Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolTip_SrcFilePath {
            get {
                return ResourceManager.GetString("ToolTip_SrcFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Src Sheet과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolTip_SrcSheet {
            get {
                return ResourceManager.GetString("ToolTip_SrcSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Swap src and dst과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ToolTip_Swap {
            get {
                return ResourceManager.GetString("ToolTip_Swap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Apply과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_Apply {
            get {
                return ResourceManager.GetString("Word_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Args과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_Args {
            get {
                return ResourceManager.GetString("Word_Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Blank과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_Blank {
            get {
                return ResourceManager.GetString("Word_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_Cancel {
            get {
                return ResourceManager.GetString("Word_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CaseSensitive과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_CaseSensitive {
            get {
                return ResourceManager.GetString("Word_CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Header Index과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_ColumnHeaderIndex {
            get {
                return ResourceManager.GetString("Word_ColumnHeaderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_Default {
            get {
                return ResourceManager.GetString("Word_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_Done {
            get {
                return ResourceManager.GetString("Word_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dst File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_DstFile {
            get {
                return ResourceManager.GetString("Word_DstFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_Edit {
            get {
                return ResourceManager.GetString("Word_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_English {
            get {
                return ResourceManager.GetString("Word_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExactMatch과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_ExactMatch {
            get {
                return ResourceManager.GetString("Word_ExactMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Executable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_Executable {
            get {
                return ResourceManager.GetString("Word_Executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_File {
            get {
                return ResourceManager.GetString("Word_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Font과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_Font {
            get {
                return ResourceManager.GetString("Word_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japanese과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_Japanese {
            get {
                return ResourceManager.GetString("Word_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launguage과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_Language {
            get {
                return ResourceManager.GetString("Word_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Match Type과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_MatchType {
            get {
                return ResourceManager.GetString("Word_MatchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max Row Header Width과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_MaxRowHeaderWidth {
            get {
                return ResourceManager.GetString("Word_MaxRowHeaderWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_Name {
            get {
                return ResourceManager.GetString("Word_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_Path {
            get {
                return ResourceManager.GetString("Word_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Regex과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_Regex {
            get {
                return ResourceManager.GetString("Word_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_Remove {
            get {
                return ResourceManager.GetString("Word_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_Reset {
            get {
                return ResourceManager.GetString("Word_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Header Index과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_RowHeaderIndex {
            get {
                return ResourceManager.GetString("Word_RowHeaderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Header Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_RowHeaderName {
            get {
                return ResourceManager.GetString("Word_RowHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_Search {
            get {
                return ResourceManager.GetString("Word_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_Setting {
            get {
                return ResourceManager.GetString("Word_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sheet과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_Sheet {
            get {
                return ResourceManager.GetString("Word_Sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sheet Index과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_SheetIndex {
            get {
                return ResourceManager.GetString("Word_SheetIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sheet Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_SheetName {
            get {
                return ResourceManager.GetString("Word_SheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Src File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_SrcFile {
            get {
                return ResourceManager.GetString("Word_SrcFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set as Startup Sheet과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_StartupSheet {
            get {
                return ResourceManager.GetString("Word_StartupSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tool과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Word_Tool {
            get {
                return ResourceManager.GetString("Word_Tool", resourceCulture);
            }
        }
    }
}
